apiVersion: v1
description: Helm chart for deployment generic app at Kubernetes
icon: https://github.com/bgcorreia/generic-app/raw/master/icon.png
maintainers:
- email: brunogomescorreia@gmail.com
  name: Bruno Correia
name: generic-app
version: v0.1.0
